# This is an example config of a model
# Python module path
model_module: "PYTORCH_EXAMPLE_MODEL"

# Model specific parameters
input_function: convert_to_pytorch
input_channels: 3
output_channels: 1
learning_rate: 0.1

# Load previous save
save_optimizer: True
load:
strict_load: True
last_epoch: -1
load_optimizer: True
update_config_loaded: False