# base
base: pytorch/templates/pytorch

# Segmentalist Config file
model_module: SEMI_SUPERVISED_DEEPLABV3P_MODEL

# Parameters
## TRAINING
learning_rate: 0.01
warm_up: True
warm_up_iterations: 20

## OUTPUT
pseudo_weight: 1.0
output_channels: 10

# Load previous save
save_optimizer: True
load:
load_optimizer: False
update_config_loaded: False
